export const abi = [
    {
      "inputs":[],
      "name":"claim",
      "outputs":[{"internalType":"bytes32","name":"requestId","type":"bytes32"}],
      "stateMutability":"payable",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"withdrawLink",
      "outputs":[],
      "stateMutability":"nonpayable",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"toggleSale",
      "outputs":[],
      "stateMutability":
      "nonpayable",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"withdrawBalance",
      "outputs":[],
      "stateMutability":"nonpayable",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"saleIsActive",
      "outputs":[{"internalType":"bool","name":"","type":"bool"}],
      "stateMutability":"view",
      "type":"function"
    },
    "event Mint(address indexed _minter, uint256 indexed _tokenID, uint256[7] random_numbers)"
]